require("dotenv").config();
const { PrismaClient } = require("@prisma/client");
const { PrismaPg } = require("@prisma/adapter-pg");
const { Pool } = require("pg");

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const products = [
  // ===================== М'ЯСО =====================
  {
    name: "Філе куряче охолоджене",
    price: 89.9,
    category: "М'ясо",
    subcategory: "М'ясо птиці",
    image: "/images/figma/products/chicken.png",
    description: "Свіже куряче філе без кісток.",
    rating: 4.5,
    isPromo: true,
    oldPrice: 109.9,
  },
  {
    name: "Стейк яловичий охолоджений",
    price: 189.9,
    category: "М'ясо",
    subcategory: "Стейки",
    image: "",
    description: "Соковитий яловичий стейк.",
    rating: 4.3,
  },
  {
    name: "Свинина, шийка охолоджена",
    price: 139.9,
    category: "М'ясо",
    subcategory: "Свинина",
    image: "",
    description: "М'яка свиняча шийка для запікання.",
    rating: 4.1,
  },
  {
    name: "Фарш курячий охолоджений",
    price: 74.9,
    category: "М'ясо",
    subcategory: "Фарш",
    image: "",
    description: "Свіжий курячий фарш.",
    rating: 4.0,
  },
  {
    name: "Крила курячі охолоджені",
    price: 64.9,
    category: "М'ясо",
    subcategory: "М'ясо птиці",
    image: "",
    description: "Соковиті курячі крила.",
    rating: 4.2,
  },
  {
    name: "Яловичина, вирізка охолоджена",
    price: 219.9,
    category: "М'ясо",
    subcategory: "Яловичина та телятина",
    image: "",
    description: "Ніжна яловича вирізка.",
    rating: 4.6,
  },
  {
    name: "Стегно куряче охолоджене",
    price: 79.9,
    category: "М'ясо",
    subcategory: "М'ясо птиці",
    image: "",
    description: "Соковите куряче стегно.",
    rating: 4.3,
  },
  {
    name: "Свинина, лопатка охолоджена",
    price: 119.9,
    category: "М'ясо",
    subcategory: "Свинина",
    image: "",
    description: "Свиняча лопатка для гуляшу.",
    rating: 4.0,
  },
  {
    name: "Фарш свинячо-яловичий",
    price: 99.9,
    category: "М'ясо",
    subcategory: "Фарш",
    image: "",
    description: "Змішаний фарш для котлет.",
    rating: 4.2,
  },
  {
    name: "Телятина, гомілка охолоджена",
    price: 249.9,
    category: "М'ясо",
    subcategory: "Яловичина та телятина",
    image: "",
    description: "Нежирна телятина.",
    rating: 4.4,
  },
  {
    name: "М'ясо шашлику зі свинини, мариноване",
    price: 149.9,
    category: "М'ясо",
    subcategory: "М'ясо для шашлику",
    image: "",
    description: "Готове до смаження м'ясо для шашлику.",
    rating: 4.5,
  },
  {
    name: "М'ясо шашлику з курки, мариноване",
    price: 109.9,
    category: "М'ясо",
    subcategory: "М'ясо для шашлику",
    image: "",
    description: "Курятина в маринаді для шашлику.",
    rating: 4.3,
  },
  {
    name: "Перепілка тушка охолоджена",
    price: 159.9,
    category: "М'ясо",
    subcategory: "Дичина",
    image: "",
    description: "Дрібна дичина, перепілка.",
    rating: 4.1,
  },
  {
    name: "Качка тушка охолоджена",
    price: 189.9,
    category: "М'ясо",
    subcategory: "Дичина",
    image: "",
    description: "Свіжа качка для запікання.",
    rating: 4.2,
  },
  {
    name: "Кролик тушка охолоджена",
    price: 229.9,
    category: "М'ясо",
    subcategory: "Кролятина",
    image: "",
    description: "Дієтична крольчатина.",
    rating: 4.3,
  },
  {
    name: "Кролик, стегенця охолоджені",
    price: 199.9,
    category: "М'ясо",
    subcategory: "Кролятина",
    image: "",
    description: "Кролячі стегенця.",
    rating: 4.1,
  },
  {
    name: "Баранина, реберця охолоджені",
    price: 279.9,
    category: "М'ясо",
    subcategory: "Баранина та ягнятина",
    image: "",
    description: "Соковиті баранячі реберця.",
    rating: 4.4,
  },
  {
    name: "Ягнятина, лопатка охолоджена",
    price: 299.9,
    category: "М'ясо",
    subcategory: "Баранина та ягнятина",
    image: "",
    description: "Молода ягнятина.",
    rating: 4.5,
  },
  {
    name: "Сало солоне з часником",
    price: 89.9,
    category: "М'ясо",
    subcategory: "Сало",
    image: "",
    description: "Класичне солоне сало.",
    rating: 4.6,
  },
  {
    name: "Сало копчене",
    price: 99.9,
    category: "М'ясо",
    subcategory: "Сало",
    image: "",
    description: "Копчене сало з прошарком.",
    rating: 4.5,
  },
  {
    name: "Печінка куряча охолоджена",
    price: 54.9,
    category: "М'ясо",
    subcategory: "Субпродукти",
    image: "",
    description: "Свіжа куряча печінка.",
    rating: 4.0,
  },
  {
    name: "Серце куряче охолоджене",
    price: 49.9,
    category: "М'ясо",
    subcategory: "Субпродукти",
    image: "",
    description: "Куряче серце для гуляшу.",
    rating: 3.9,
  },
  {
    name: "Котлети куряча по-київськи, напівфабрикат",
    price: 119.9,
    category: "М'ясо",
    subcategory: "М'ясні напівфабрикати",
    image: "",
    description: "Готова заморожена котлета.",
    rating: 4.3,
  },
  {
    name: "Тефтелі м'ясні, напівфабрикат",
    price: 99.9,
    category: "М'ясо",
    subcategory: "М'ясні напівфабрикати",
    image: "",
    description: "Заморожені тефтелі.",
    rating: 4.1,
  },
  {
    name: "Філе куряче без шкіри, дієтичне",
    price: 84.9,
    category: "М'ясо",
    subcategory: "Дієтичне м'ясо",
    image: "",
    description: "Низькокалорійне куряче філе.",
    rating: 4.4,
  },
  {
    name: "Грудка індички охолоджена",
    price: 149.9,
    category: "М'ясо",
    subcategory: "Дієтичне м'ясо",
    image: "",
    description: "Дієтична грудка індички.",
    rating: 4.5,
  },

  // ===================== СВІЖА РИБА =====================
  {
    name: "Сьомга, стейк охолоджений",
    price: 94.9,
    category: "Свіжа риба",
    subcategory: "Свіжа риба",
    image: "/images/figma/products/fish/fish-1.jpg",
    description: "Свіжий стейк сьомги.",
    rating: 4.3,
  },
  {
    name: "Сьомга (лосось) філе охолоджене",
    price: 109.9,
    category: "Свіжа риба",
    subcategory: "Свіжа риба",
    image: "/images/figma/products/fish/fish-2.jpg",
    description: "Ніжне філе сьомги без кісток.",
    rating: 3.9,
  },
  {
    name: "Форель, стейк охолоджений",
    price: 98.89,
    category: "Свіжа риба",
    subcategory: "Свіжа риба",
    image: "/images/figma/products/fish/fish-3.jpg",
    description: "Стейк форелі преміум якості.",
    rating: 4.3,
  },
  {
    name: "Форель, філе охолоджене",
    price: 109.9,
    category: "Свіжа риба",
    subcategory: "Свіжа риба",
    image: "/images/figma/products/fish/fish-4.jpg",
    description: "Свіже філе форелі.",
    rating: 3.9,
  },
  {
    name: "Голець арктичний охолоджений",
    price: 109.9,
    category: "Свіжа риба",
    subcategory: "Свіжа риба",
    image: "/images/figma/products/fish/fish-5.jpg",
    description: "Арктичний голець.",
    rating: 4.1,
  },
  {
    name: "Форель, філе в упаковці",
    price: 119.9,
    category: "Свіжа риба",
    subcategory: "Заморожена риба",
    image: "/images/figma/products/fish/fish-6.jpg",
    description: "Філе форелі у вакуумній упаковці.",
    rating: 3.4,
  },
  {
    name: "Лосось шотландський, стейки",
    price: 259.9,
    category: "Свіжа риба",
    subcategory: "Свіжа риба",
    image: "/images/figma/products/fish/fish-7.jpg",
    description: "Преміальний лосось.",
    rating: 4.8,
  },
  {
    name: "Лосось, хребти дефростовані",
    price: 16.9,
    category: "Свіжа риба",
    subcategory: "Рибні напівфабрикати",
    image: "/images/figma/products/fish/fish-8.jpg",
    description: "Хребти лосося для бульйонів.",
    rating: 3.4,
  },
  {
    name: "Скумбрія заморожена",
    price: 64.9,
    category: "Свіжа риба",
    subcategory: "Заморожена риба",
    image: "",
    description: "Заморожена скумбрія.",
    rating: 4.2,
  },
  {
    name: "Хек заморожений, тушка",
    price: 54.9,
    category: "Свіжа риба",
    subcategory: "Заморожена риба",
    image: "",
    description: "Біла риба хек.",
    rating: 4.0,
  },
  {
    name: "Креветки очищені заморожені",
    price: 189.9,
    category: "Свіжа риба",
    subcategory: "Морепродукти та молюски",
    image: "",
    description: "Чищені креветки 200 шт/кг.",
    rating: 4.6,
  },
  {
    name: "Мідії в стулках заморожені",
    price: 159.9,
    category: "Свіжа риба",
    subcategory: "Морепродукти та молюски",
    image: "",
    description: "Морські мідії.",
    rating: 4.3,
  },
  {
    name: "Ікра лосося червона",
    price: 459.9,
    category: "Свіжа риба",
    subcategory: "Ікра",
    image: "",
    description: "Делікатесна червона ікра.",
    rating: 4.7,
  },
  {
    name: "Ікра мойви чорна",
    price: 99.9,
    category: "Свіжа риба",
    subcategory: "Ікра",
    image: "",
    description: "Доступна чорна ікра мойви.",
    rating: 4.0,
  },
  {
    name: "Скумбрія копчена",
    price: 89.9,
    category: "Свіжа риба",
    subcategory: "Копчена і в'ялена риба",
    image: "",
    description: "Холодного копчення скумбрія.",
    rating: 4.5,
  },
  {
    name: "Тарань в'ялена",
    price: 119.9,
    category: "Свіжа риба",
    subcategory: "Копчена і в'ялена риба",
    image: "",
    description: "В'ялена тарань до пива.",
    rating: 4.4,
  },
  {
    name: "Палички крабові",
    price: 49.9,
    category: "Свіжа риба",
    subcategory: "Крабові палички",
    image: "",
    description: "Класичні крабові палички.",
    rating: 4.1,
  },
  {
    name: "Філе риби в кляри, напівфабрикат",
    price: 99.9,
    category: "Свіжа риба",
    subcategory: "Рибні напівфабрикати",
    image: "",
    description: "Готова до смаження риба.",
    rating: 4.0,
  },
  {
    name: "Салат з морської капусти",
    price: 64.9,
    category: "Свіжа риба",
    subcategory: "Приготовлена риба, салат",
    image: "",
    description: "Готовий салат з морської капусти.",
    rating: 4.2,
  },
  {
    name: "Лобстер варено-морожений",
    price: 899.9,
    category: "Свіжа риба",
    subcategory: "Устриці та лобстери",
    image: "",
    description: "Преміальний лобстер.",
    rating: 4.8,
  },
  {
    name: "Устриці свіжі, 6 шт",
    price: 459.9,
    category: "Свіжа риба",
    subcategory: "Устриці та лобстери",
    image: "",
    description: "Свіжі французькі устриці.",
    rating: 4.6,
  },
  {
    name: "Равлики Helix заморожені",
    price: 349.9,
    category: "Свіжа риба",
    subcategory: "Заморожені равлики",
    image: "",
    description: "Делікатесні равлики.",
    rating: 4.3,
  },

  // ===================== ФРУКТИ, ОВОЧІ =====================
  {
    name: "Виноград білий без кісточки",
    price: 120.12,
    category: "Фрукти, овочі",
    subcategory: "Фрукти",
    image: "/images/figma/products/grapes.png",
    description: "Соковитий білий виноград.",
    rating: 4.4,
    isPromo: true,
    oldPrice: 154.0,
  },
  {
    name: "Томати чері свіжі",
    price: 72.53,
    category: "Фрукти, овочі",
    subcategory: "Овочі",
    image: "/images/figma/products/tomatoes.png",
    description: "Свіжі томати чері.",
    rating: 4.2,
    isPromo: true,
    oldPrice: 92.9,
  },
  {
    name: "Банани свіжі",
    price: 45.9,
    category: "Фрукти, овочі",
    subcategory: "Фрукти",
    image: "",
    description: "Стиглі банани.",
    rating: 4.0,
  },
  {
    name: "Яблука Голден свіжі",
    price: 38.9,
    category: "Фрукти, овочі",
    subcategory: "Фрукти",
    image: "",
    description: "Солодкі яблука сорту Голден.",
    rating: 4.1,
  },
  {
    name: "Апельсини свіжі 1кг",
    price: 59.9,
    category: "Фрукти, овочі",
    subcategory: "Фрукти",
    image: "",
    description: "Соковиті апельсини.",
    rating: 4.3,
  },
  {
    name: "Огірки свіжі",
    price: 34.9,
    category: "Фрукти, овочі",
    subcategory: "Овочі",
    image: "",
    description: "Хрусткі свіжі огірки.",
    rating: 4.1,
  },
  {
    name: "Перець болгарський червоний",
    price: 49.9,
    category: "Фрукти, овочі",
    subcategory: "Овочі",
    image: "",
    description: "Соковитий болгарський перець.",
    rating: 4.2,
  },
  {
    name: "Картопля молода 1кг",
    price: 28.9,
    category: "Фрукти, овочі",
    subcategory: "Овочі",
    image: "",
    description: "Свіжа молода картопля.",
    rating: 4.0,
  },
  {
    name: "Малина свіжа 250г",
    price: 89.9,
    category: "Фрукти, овочі",
    subcategory: "Ягоди",
    image: "",
    description: "Соковита свіжа малина.",
    rating: 4.5,
  },
  {
    name: "Чорниця свіжа 250г",
    price: 99.9,
    category: "Фрукти, овочі",
    subcategory: "Ягоди",
    image: "",
    description: "Лісова чорниця.",
    rating: 4.6,
  },
  {
    name: "Лимони свіжі 500г",
    price: 49.9,
    category: "Фрукти, овочі",
    subcategory: "Сезонні овочі, фрукти",
    image: "",
    description: "Стиглі соковиті лимони.",
    rating: 4.3,
  },
  {
    name: "Гарбуз свіжий, частина",
    price: 24.9,
    category: "Фрукти, овочі",
    subcategory: "Сезонні овочі, фрукти",
    image: "",
    description: "Сезонний гарбуз.",
    rating: 4.0,
  },
  {
    name: "Кріп свіжий, пучок",
    price: 19.9,
    category: "Фрукти, овочі",
    subcategory: "Зелень і салати",
    image: "",
    description: "Ароматний свіжий кріп.",
    rating: 4.2,
  },
  {
    name: "Салат Айсберг",
    price: 39.9,
    category: "Фрукти, овочі",
    subcategory: "Зелень і салати",
    image: "",
    description: "Хрусткий салат Айсберг.",
    rating: 4.1,
  },
  {
    name: "Гриби печериці свіжі 500г",
    price: 64.9,
    category: "Фрукти, овочі",
    subcategory: "Гриби",
    image: "",
    description: "Свіжі печериці.",
    rating: 4.3,
  },
  {
    name: "Гриби лисички заморожені 400г",
    price: 119.9,
    category: "Фрукти, овочі",
    subcategory: "Гриби",
    image: "",
    description: "Лісові лисички.",
    rating: 4.4,
  },
  {
    name: "Смузі ягідний 250мл",
    price: 54.9,
    category: "Фрукти, овочі",
    subcategory: "Смузі і фреші",
    image: "",
    description: "Натуральний ягідний смузі.",
    rating: 4.5,
  },
  {
    name: "Фреш апельсиновий 300мл",
    price: 64.9,
    category: "Фрукти, овочі",
    subcategory: "Смузі і фреші",
    image: "",
    description: "Свіжовичавлений апельсиновий сік.",
    rating: 4.4,
  },
  {
    name: "Снеки яблучні сушені 50г",
    price: 44.9,
    category: "Фрукти, овочі",
    subcategory: "Фруктові, овочеві снеки",
    image: "",
    description: "Сушені яблучні чипси.",
    rating: 4.1,
  },
  {
    name: "Горіхи мікс 200г",
    price: 89.9,
    category: "Фрукти, овочі",
    subcategory: "Горіхи і сухофрукти",
    image: "",
    description: "Асорті горіхів.",
    rating: 4.5,
  },
  {
    name: "Курага сушена 200г",
    price: 69.9,
    category: "Фрукти, овочі",
    subcategory: "Горіхи і сухофрукти",
    image: "",
    description: "Натуральна курага.",
    rating: 4.3,
  },
  {
    name: "Огірки солені бочкові 500г",
    price: 54.9,
    category: "Фрукти, овочі",
    subcategory: "Соління",
    image: "",
    description: "Класичні бочкові огірки.",
    rating: 4.4,
  },
  {
    name: "Капуста квашена 500г",
    price: 44.9,
    category: "Фрукти, овочі",
    subcategory: "Соління",
    image: "",
    description: "Домашня квашена капуста.",
    rating: 4.2,
  },

  // ===================== МОЛОЧКА ТА ЯЙЦЯ =====================
  {
    name: "Молоко Галичина 2.5%",
    price: 42.9,
    category: "Молочка та яйця",
    subcategory: "Молоко, вершки",
    image: "",
    description: "Пастеризоване молоко.",
    rating: 4.5,
  },
  {
    name: "Яйця курячі С1, 10 шт",
    price: 64.9,
    category: "Молочка та яйця",
    subcategory: "Яйця",
    image: "",
    description: "Свіжі курячі яйця.",
    rating: 4.3,
  },
  {
    name: "Сметана 20% Президент",
    price: 38.9,
    category: "Молочка та яйця",
    subcategory: "Сметана",
    image: "",
    description: "Густа сметана.",
    rating: 4.2,
  },
  {
    name: "Кефір 1% Яготинський",
    price: 29.9,
    category: "Молочка та яйця",
    subcategory: "Кисломолочні напої",
    image: "",
    description: "Легкий кефір.",
    rating: 4.0,
  },
  {
    name: "Масло вершкове 82.5% 200г",
    price: 89.9,
    category: "Молочка та яйця",
    subcategory: "Масло, маргарин, спред",
    image: "",
    description: "Натуральне вершкове масло.",
    rating: 4.6,
  },
  {
    name: "Йогурт Activia натуральний",
    price: 34.9,
    category: "Молочка та яйця",
    subcategory: "Йогурти, десерти",
    image: "",
    description: "Корисний натуральний йогурт.",
    rating: 4.4,
  },
  {
    name: "Вершки 33% для збивання",
    price: 54.9,
    category: "Молочка та яйця",
    subcategory: "Молоко, вершки",
    image: "",
    description: "Жирні вершки для десертів.",
    rating: 4.5,
  },
  {
    name: "Яйця перепелині, 20 шт",
    price: 54.9,
    category: "Молочка та яйця",
    subcategory: "Яйця",
    image: "",
    description: "Дрібні перепелині яйця.",
    rating: 4.3,
  },
  {
    name: "Сир кисломолочний 9% 400г",
    price: 74.9,
    category: "Молочка та яйця",
    subcategory: "Сир Кисломолочний, сирок",
    image: "",
    description: "Зернистий кисломолочний сир.",
    rating: 4.4,
  },
  {
    name: "Сирки глазуровані шоколадні",
    price: 14.9,
    category: "Молочка та яйця",
    subcategory: "Глазуровані сирки",
    image: "",
    description: "Класичні глазуровані сирки.",
    rating: 4.2,
  },
  {
    name: "Молоко згущене вареное",
    price: 49.9,
    category: "Молочка та яйця",
    subcategory: "Згущене молоко",
    image: "",
    description: "Класична варена згущенка.",
    rating: 4.6,
  },
  {
    name: "Пюре дитяче молочне",
    price: 24.9,
    category: "Молочка та яйця",
    subcategory: "Молочні продукти для дітей",
    image: "",
    description: "Молочне пюре для малюків.",
    rating: 4.3,
  },
  {
    name: "Вареники з сиром, напівфабрикат",
    price: 84.9,
    category: "Молочка та яйця",
    subcategory: "Напівфабрикати власного виробництва",
    image: "",
    description: "Домашні вареники з сиром.",
    rating: 4.4,
  },
  {
    name: "Молоко кокосове рослинне",
    price: 79.9,
    category: "Молочка та яйця",
    subcategory: "Безмолочна продукція",
    image: "",
    description: "Рослинна альтернатива молоку.",
    rating: 4.1,
  },

  // ===================== СИРИ =====================
  {
    name: "Сир Гауда нарізка",
    price: 89.9,
    category: "Сири",
    subcategory: "Тверді і напівтверді сири",
    image: "",
    description: "Ніжний сир Гауда.",
    rating: 4.3,
  },
  {
    name: "Сир Моцарела куля",
    price: 74.9,
    category: "Сири",
    subcategory: "Розсільні сири",
    image: "",
    description: "Свіжа моцарела.",
    rating: 4.6,
  },
  {
    name: "Сир Пармезан тертий 100г",
    price: 129.9,
    category: "Сири",
    subcategory: "Тверді і напівтверді сири",
    image: "",
    description: "Тертий пармезан.",
    rating: 4.7,
  },
  {
    name: "Сир Брі м'який 125г",
    price: 149.9,
    category: "Сири",
    subcategory: "Сири з пліснявою",
    image: "",
    description: "Вершковий сир Брі.",
    rating: 4.4,
  },
  {
    name: "Сир Чеддер нарізка",
    price: 99.9,
    category: "Сири",
    subcategory: "Тверді і напівтверді сири",
    image: "",
    description: "Пікантний сир Чеддер.",
    rating: 4.3,
  },
  {
    name: "Сир Дор Блю з пліснявою",
    price: 169.9,
    category: "Сири",
    subcategory: "Сири з пліснявою",
    image: "",
    description: "Гострий сир з голубою пліснявою.",
    rating: 4.2,
  },
  {
    name: "Сир Фета розсільний 200г",
    price: 84.9,
    category: "Сири",
    subcategory: "Козячі і овечі сири",
    image: "",
    description: "Грецький розсільний сир.",
    rating: 4.5,
  },
  {
    name: "Сир козячий м'який 150г",
    price: 119.9,
    category: "Сири",
    subcategory: "Козячі і овечі сири",
    image: "",
    description: "Ніжний козячий сир.",
    rating: 4.4,
  },
  {
    name: "Сир крем-сир класичний 200г",
    price: 64.9,
    category: "Сири",
    subcategory: "Крем-сири",
    image: "",
    description: "Вершковий крем-сир.",
    rating: 4.5,
  },
  {
    name: "Сир плавлений Дружба 90г",
    price: 19.9,
    category: "Сири",
    subcategory: "Сири плавлені",
    image: "",
    description: "Класичний плавлений сир.",
    rating: 4.0,
  },
  {
    name: "Сирки дитячі творожні",
    price: 29.9,
    category: "Сири",
    subcategory: "Сири для дітей",
    image: "",
    description: "М'які сирки для дітей.",
    rating: 4.3,
  },
  {
    name: "Набір сирів асорті 300г",
    price: 219.9,
    category: "Сири",
    subcategory: "Набори сирів",
    image: "",
    description: "Дегустаційний набір сирів.",
    rating: 4.6,
  },

  // ===================== ХЛІБ ТА ВИПІЧКА =====================
  {
    name: "Хліб Бородинський",
    price: 28.9,
    category: "Хліб та випічка",
    subcategory: "Хлібобулочні вироби",
    image: "",
    description: "Житній хліб.",
    rating: 4.5,
  },
  {
    name: "Батон нарізний",
    price: 22.9,
    category: "Хліб та випічка",
    subcategory: "Хлібобулочні вироби",
    image: "",
    description: "М'який пшеничний батон.",
    rating: 4.2,
  },
  {
    name: "Круасан масляний",
    price: 18.9,
    category: "Хліб та випічка",
    subcategory: "Випічка",
    image: "",
    description: "Листковий круасан.",
    rating: 4.6,
  },
  {
    name: "Булочки для бургера 4 шт",
    price: 34.9,
    category: "Хліб та випічка",
    subcategory: "Хлібобулочні вироби",
    image: "",
    description: "М'які булочки.",
    rating: 4.1,
  },
  {
    name: "Хліб цільнозерновий",
    price: 32.9,
    category: "Хліб та випічка",
    subcategory: "Хлібобулочні вироби",
    image: "",
    description: "Корисний цільнозерновий хліб.",
    rating: 4.4,
  },
  {
    name: "Лаваш тонкий вірменський",
    price: 24.9,
    category: "Хліб та випічка",
    subcategory: "Хлібобулочні вироби",
    image: "",
    description: "Тонкий лаваш.",
    rating: 4.2,
  },
  {
    name: "Коржі для піци 2 шт",
    price: 39.9,
    category: "Хліб та випічка",
    subcategory: "Коржі, основа для піци",
    image: "",
    description: "Готова основа для піци.",
    rating: 4.1,
  },
  {
    name: "Сушка солодка 300г",
    price: 29.9,
    category: "Хліб та випічка",
    subcategory: "Сушка, хлібці пряники",
    image: "",
    description: "Класична сушка з маком.",
    rating: 4.0,
  },
  {
    name: "Хлібці рисові 100г",
    price: 34.9,
    category: "Хліб та випічка",
    subcategory: "Сушка, хлібці пряники",
    image: "",
    description: "Дієтичні рисові хлібці.",
    rating: 4.2,
  },

  // ===================== КОВБАСИ ТА ДЕЛІКАТЕСИ =====================
  {
    name: "Ковбаса Докторська варена",
    price: 94.9,
    category: "Ковбаси та делікатеси",
    subcategory: "Ковбаси",
    image: "",
    description: "Класична варена ковбаса.",
    rating: 4.2,
  },
  {
    name: "Шинка свиняча копчена",
    price: 189.9,
    category: "Ковбаси та делікатеси",
    subcategory: "М'ясні делікатеси",
    image: "",
    description: "Копчена свиняча шинка.",
    rating: 4.5,
  },
  {
    name: "Салямі Мілано нарізка",
    price: 149.9,
    category: "Ковбаси та делікатеси",
    subcategory: "М'ясо-ковбасна нарізка",
    image: "",
    description: "Італійська салямі.",
    rating: 4.4,
  },
  {
    name: "Сосиски Молочні 5 шт",
    price: 64.9,
    category: "Ковбаси та делікатеси",
    subcategory: "Сосиски і сардельки",
    image: "",
    description: "Ніжні молочні сосиски.",
    rating: 4.0,
  },
  {
    name: "Бекон копчений нарізка",
    price: 119.9,
    category: "Ковбаси та делікатеси",
    subcategory: "М'ясо-ковбасна нарізка",
    image: "",
    description: "Ароматний копчений бекон.",
    rating: 4.5,
  },
  {
    name: "Паштет курячий 200г",
    price: 54.9,
    category: "Ковбаси та делікатеси",
    subcategory: "М'ясні делікатеси",
    image: "",
    description: "Ніжний курячий паштет.",
    rating: 4.1,
  },
  {
    name: "Хамон Серрано нарізка 80г",
    price: 249.9,
    category: "Ковбаси та делікатеси",
    subcategory: "Хамон",
    image: "",
    description: "Іспанський хамон серрано.",
    rating: 4.7,
  },
  {
    name: "Хамон Іберіко нарізка 60г",
    price: 399.9,
    category: "Ковбаси та делікатеси",
    subcategory: "Хамон",
    image: "",
    description: "Преміальний хамон іберіко.",
    rating: 4.8,
  },
  {
    name: "Сало копчене з паприкою",
    price: 109.9,
    category: "Ковбаси та делікатеси",
    subcategory: "Сало",
    image: "",
    description: "Гостре копчене сало.",
    rating: 4.4,
  },
  {
    name: "Снеки м'ясні сушені 50г",
    price: 64.9,
    category: "Ковбаси та делікатеси",
    subcategory: "М'ясні снеки",
    image: "",
    description: "Сушене м'ясо снек.",
    rating: 4.2,
  },
  {
    name: "Ковбаски веганські рослинні",
    price: 89.9,
    category: "Ковбаси та делікатеси",
    subcategory: "Веган",
    image: "",
    description: "Рослинна альтернатива ковбасі.",
    rating: 3.9,
  },

  // ===================== ГОТОВІ СТРАВИ І КУЛІНАРІЯ =====================
  {
    name: "Піца Маргарита заморожена",
    price: 129.9,
    category: "Готові страви і кулінарія",
    subcategory: "Суші, піца, бургери",
    image: "",
    description: "Класична піца.",
    rating: 4.1,
  },
  {
    name: "Вареники з картоплею 500г",
    price: 74.9,
    category: "Готові страви і кулінарія",
    subcategory: "Напівфабрикати власного виробництва",
    image: "",
    description: "Домашні вареники.",
    rating: 4.4,
  },
  {
    name: "Котлети курячі заморожені",
    price: 89.9,
    category: "Готові страви і кулінарія",
    subcategory: "Другі страви",
    image: "",
    description: "Соковиті курячі котлети.",
    rating: 4.2,
  },
  {
    name: "Суші-сет Філадельфія 8 шт",
    price: 189.9,
    category: "Готові страви і кулінарія",
    subcategory: "Суші, піца, бургери",
    image: "",
    description: "Класичні роли Філадельфія.",
    rating: 4.6,
  },
  {
    name: "Салат Олів'є 200г",
    price: 64.9,
    category: "Готові страви і кулінарія",
    subcategory: "Салати та закуски",
    image: "",
    description: "Класичний салат Олів'є.",
    rating: 4.0,
  },
  {
    name: "Млинці з м'ясом заморожені",
    price: 79.9,
    category: "Готові страви і кулінарія",
    subcategory: "Млинці, сирники, запіканки",
    image: "",
    description: "Домашні млинці.",
    rating: 4.3,
  },
  {
    name: "Борщ український готовий 500г",
    price: 59.9,
    category: "Готові страви і кулінарія",
    subcategory: "Перші страви",
    image: "",
    description: "Гарячий український борщ.",
    rating: 4.5,
  },
  {
    name: "Суп-крем грибний 400г",
    price: 54.9,
    category: "Готові страви і кулінарія",
    subcategory: "Перші страви",
    image: "",
    description: "Нечний грибний крем-суп.",
    rating: 4.3,
  },
  {
    name: "Сирники з ягодами 300г",
    price: 69.9,
    category: "Готові страви і кулінарія",
    subcategory: "Млинці, сирники, запіканки",
    image: "",
    description: "Готові сирники з підливою.",
    rating: 4.4,
  },
  {
    name: "Тірамісу класичний 150г",
    price: 89.9,
    category: "Готові страви і кулінарія",
    subcategory: "Десерти та напої",
    image: "",
    description: "Італійський десерт тірамісу.",
    rating: 4.6,
  },
  {
    name: "Лимонад домашній 500мл",
    price: 44.9,
    category: "Готові страви і кулінарія",
    subcategory: "Десерти та напої",
    image: "",
    description: "Освіжаючий лимонад.",
    rating: 4.3,
  },
  {
    name: "Сніданок англійський набір",
    price: 99.9,
    category: "Готові страви і кулінарія",
    subcategory: "Сніданки та комплексні обіди",
    image: "",
    description: "Готовий набір для сніданку.",
    rating: 4.2,
  },
  {
    name: "Пиріжки з вишнею 4 шт",
    price: 49.9,
    category: "Готові страви і кулінарія",
    subcategory: "Пироги, пиріжки, випічка",
    image: "",
    description: "Домашні пиріжки з вишнею.",
    rating: 4.5,
  },
  {
    name: "Голубці з м'ясом, напівфабрикат",
    price: 94.9,
    category: "Готові страви і кулінарія",
    subcategory: "Напівфабрикати власного виробництва",
    image: "",
    description: "Готові голубці.",
    rating: 4.3,
  },

  // ===================== БАКАЛІЯ І КОНСЕРВИ =====================
  {
    name: "Рис круглозернистий 1кг",
    price: 44.9,
    category: "Бакалія і консерви",
    subcategory: "Крупи",
    image: "",
    description: "Білий круглозернистий рис.",
    rating: 4.3,
  },
  {
    name: "Макарони Пенне 500г",
    price: 29.9,
    category: "Бакалія і консерви",
    subcategory: "Макаронні вироби",
    image: "",
    description: "Класичні макарони.",
    rating: 4.2,
  },
  {
    name: "Тунець консервований в олії",
    price: 54.9,
    category: "Бакалія і консерви",
    subcategory: "Консервація",
    image: "",
    description: "Ніжний тунець.",
    rating: 4.5,
  },
  {
    name: "Квасоля червона консервована",
    price: 32.9,
    category: "Бакалія і консерви",
    subcategory: "Консервація",
    image: "",
    description: "Готова червона квасоля.",
    rating: 4.0,
  },
  {
    name: "Гречка ядриця 800г",
    price: 49.9,
    category: "Бакалія і консерви",
    subcategory: "Крупи",
    image: "",
    description: "Смачна гречана крупа.",
    rating: 4.5,
  },
  {
    name: "Олія соняшникова 1л",
    price: 59.9,
    category: "Бакалія і консерви",
    subcategory: "Олія та оцет",
    image: "",
    description: "Рафінована соняшникова олія.",
    rating: 4.2,
  },
  {
    name: "Борошно пшеничне вищого сорту 1кг",
    price: 34.9,
    category: "Бакалія і консерви",
    subcategory: "Борошно",
    image: "",
    description: "Якісне пшеничне борошно.",
    rating: 4.3,
  },
  {
    name: "Цукор білий 1кг",
    price: 29.9,
    category: "Бакалія і консерви",
    subcategory: "Сіль, цукор",
    image: "",
    description: "Класичний білий цукор.",
    rating: 4.1,
  },
  {
    name: "Сіль кухонна йодована 1кг",
    price: 14.9,
    category: "Бакалія і консерви",
    subcategory: "Сіль, цукор",
    image: "",
    description: "Йодована кухонна сіль.",
    rating: 4.0,
  },
  {
    name: "Оцет яблучний 500мл",
    price: 39.9,
    category: "Бакалія і консерви",
    subcategory: "Олія та оцет",
    image: "",
    description: "Натуральний яблучний оцет.",
    rating: 4.2,
  },
  {
    name: "Варення вишневе 400г",
    price: 64.9,
    category: "Бакалія і консерви",
    subcategory: "Консервовані фрукти, варення, мед",
    image: "",
    description: "Домашнє вишневе варення.",
    rating: 4.5,
  },
  {
    name: "Мед квітковий натуральний 500г",
    price: 149.9,
    category: "Бакалія і консерви",
    subcategory: "Консервовані фрукти, варення, мед",
    image: "",
    description: "Натуральний квітковий мед.",
    rating: 4.7,
  },
  {
    name: "Локшина швидкого приготування",
    price: 19.9,
    category: "Бакалія і консерви",
    subcategory: "Їжа швидкого приготування",
    image: "",
    description: "Локшина у склянці.",
    rating: 3.8,
  },
  {
    name: "Соус соєвий для суші 200мл",
    price: 49.9,
    category: "Бакалія і консерви",
    subcategory: "Азійська кухня",
    image: "",
    description: "Класичний соус для суші.",
    rating: 4.4,
  },

  // ===================== СОУСИ І СПЕЦІЇ =====================
  {
    name: "Кетчуп томатний Чумак",
    price: 38.9,
    category: "Соуси і спеції",
    subcategory: "Соуси, заправки",
    image: "",
    description: "Класичний томатний кетчуп.",
    rating: 4.3,
  },
  {
    name: "Майонез Торчин 67%",
    price: 44.9,
    category: "Соуси і спеції",
    subcategory: "Соуси, заправки",
    image: "",
    description: "Густий майонез.",
    rating: 4.1,
  },
  {
    name: "Соєвий соус Кіккоман 150мл",
    price: 69.9,
    category: "Соуси і спеції",
    subcategory: "Соуси, заправки",
    image: "",
    description: "Японський соєвий соус.",
    rating: 4.7,
  },
  {
    name: "Перець чорний мелений 50г",
    price: 24.9,
    category: "Соуси і спеції",
    subcategory: "Спеції",
    image: "",
    description: "Ароматний чорний перець.",
    rating: 4.4,
  },
  {
    name: "Гірчиця діжонська 200г",
    price: 49.9,
    category: "Соуси і спеції",
    subcategory: "Соуси, заправки",
    image: "",
    description: "Французька діжонська гірчиця.",
    rating: 4.5,
  },
  {
    name: "Паприка солодка мелена 40г",
    price: 29.9,
    category: "Соуси і спеції",
    subcategory: "Спеції",
    image: "",
    description: "Ароматна солодка паприка.",
    rating: 4.3,
  },
  {
    name: "Ванілін у пакетику 2г",
    price: 9.9,
    category: "Соуси і спеції",
    subcategory: "Все для випічки",
    image: "",
    description: "Натуральний ванілін.",
    rating: 4.0,
  },
  {
    name: "Розпушувач тіста 10г",
    price: 12.9,
    category: "Соуси і спеції",
    subcategory: "Все для випічки",
    image: "",
    description: "Розпушувач для тіста.",
    rating: 4.1,
  },
  {
    name: "Панірувальні сухарі 200г",
    price: 24.9,
    category: "Соуси і спеції",
    subcategory: "Панірування",
    image: "",
    description: "Класичні сухарі для панірування.",
    rating: 4.2,
  },

  // ===================== СОЛОДОЩІ =====================
  {
    name: "Шоколад Roshen молочний",
    price: 54.9,
    category: "Солодощі",
    subcategory: "Шоколад",
    image: "",
    description: "Ніжний молочний шоколад.",
    rating: 4.5,
  },
  {
    name: "Цукерки Рошен асорті 200г",
    price: 89.9,
    category: "Солодощі",
    subcategory: "Цукерки",
    image: "",
    description: "Асорті цукерок.",
    rating: 4.3,
  },
  {
    name: "Печиво Юбілейне 400г",
    price: 44.9,
    category: "Солодощі",
    subcategory: "Печиво, вафлі, бісквіти",
    image: "",
    description: "Класичне вівсяне печиво.",
    rating: 4.1,
  },
  {
    name: "Мармелад фруктовий 300г",
    price: 39.9,
    category: "Солодощі",
    subcategory: "Зефір, мармелад, пастила",
    image: "",
    description: "Натуральний мармелад.",
    rating: 4.0,
  },
  {
    name: "Вафлі Артек з горіховим кремом",
    price: 34.9,
    category: "Солодощі",
    subcategory: "Печиво, вафлі, бісквіти",
    image: "",
    description: "Хрусткі вафлі.",
    rating: 4.2,
  },
  {
    name: "Халва соняшникова 300г",
    price: 49.9,
    category: "Солодощі",
    subcategory: "Східні солодощі",
    image: "",
    description: "Класична соняшникова халва.",
    rating: 4.3,
  },
  {
    name: "Торт Київський 800г",
    price: 249.9,
    category: "Солодощі",
    subcategory: "Власна Кондитерська",
    image: "",
    description: "Легендарний Київський торт.",
    rating: 4.8,
  },
  {
    name: "Тістечко Наполеон, шт",
    price: 39.9,
    category: "Солодощі",
    subcategory: "Власна Кондитерська",
    image: "",
    description: "Шарове тістечко Наполеон.",
    rating: 4.5,
  },
  {
    name: "Зефір ванільний 300г",
    price: 54.9,
    category: "Солодощі",
    subcategory: "Зефір, мармелад, пастила",
    image: "",
    description: "Повітряний ванільний зефір.",
    rating: 4.4,
  },
  {
    name: "Рахат-лукум асорті 200г",
    price: 79.9,
    category: "Солодощі",
    subcategory: "Східні солодощі",
    image: "",
    description: "Східна солодість рахат-лукум.",
    rating: 4.5,
  },
  {
    name: "Жувальна гумка Orbit",
    price: 24.9,
    category: "Солодощі",
    subcategory: "Жувальна гумка",
    image: "",
    description: "М'ятна жувальна гумка.",
    rating: 4.0,
  },

  // ===================== ЗДОРОВЕ ХАРЧУВАННЯ =====================
  {
    name: "Гранола з горіхами 400г",
    price: 89.9,
    category: "Здорове харчування",
    subcategory: "Органічна їжа",
    image: "",
    description: "Корисна гранола.",
    rating: 4.6,
  },
  {
    name: "Мигдаль смажений 150г",
    price: 74.9,
    category: "Здорове харчування",
    subcategory: "Органічна їжа",
    image: "",
    description: "Хрусткий смажений мигдаль.",
    rating: 4.5,
  },
  {
    name: "Йогурт грецький 0% 300г",
    price: 49.9,
    category: "Здорове харчування",
    subcategory: "Дієтичне харчування",
    image: "",
    description: "Натуральний грецький йогурт.",
    rating: 4.4,
  },
  {
    name: "Протеїновий батончик шоколад",
    price: 64.9,
    category: "Здорове харчування",
    subcategory: "Дієтичне харчування",
    image: "",
    description: "Білковий батончик.",
    rating: 4.2,
  },
  {
    name: "Насіння чіа 200г",
    price: 79.9,
    category: "Здорове харчування",
    subcategory: "Органічна їжа",
    image: "",
    description: "Суперфуд насіння чіа.",
    rating: 4.5,
  },
  {
    name: "Авокадо свіже 1 шт",
    price: 54.9,
    category: "Здорове харчування",
    subcategory: "Веганські продукти",
    image: "",
    description: "Стигле авокадо.",
    rating: 4.3,
  },
  {
    name: "Тофу натуральний 300г",
    price: 69.9,
    category: "Здорове харчування",
    subcategory: "Веганські продукти",
    image: "",
    description: "Соєвий тофу.",
    rating: 4.1,
  },
  {
    name: "Молоко безлактозне 1л",
    price: 64.9,
    category: "Здорове харчування",
    subcategory: "Безлактозні продукти",
    image: "",
    description: "Молоко без лактози.",
    rating: 4.3,
  },
  {
    name: "Хліб безглютеновий 300г",
    price: 89.9,
    category: "Здорове харчування",
    subcategory: "Безглютенові продукти",
    image: "",
    description: "Хліб без глютену.",
    rating: 4.0,
  },
  {
    name: "Печиво без цукру 200г",
    price: 79.9,
    category: "Здорове харчування",
    subcategory: "Без доданого цукру",
    image: "",
    description: "Печиво на стевії.",
    rating: 4.2,
  },
];

const recipes = [
  {
    title: "Сирні бейгли",
    image: "/images/figma/recipes/cheese-bagels.jpg",
    description: "Хрусткі домашні бейгли з вершковим сиром.",
  },
  {
    title: "Паста-салат з куркою",
    image: "/images/figma/recipes/pasta-salad.jpg",
    description: "Легкий салат з пастою і курячим філе.",
  },
  {
    title: "Фалафель",
    image: "/images/figma/recipes/falafel.jpg",
    description: "Хрусткі шарики з нуту з ароматними спеціями.",
  },
  {
    title: "Фісташкове тирамісу",
    image: "/images/figma/recipes/pistachio-tiramisu.jpg",
    description: "Італійський десерт з фісташковим присмаком.",
  },
  {
    title: "Відкритий сендвіч з редискою та авокадо",
    image: "/images/figma/recipes/radish-avocado-sandwich.jpg",
    description: "Свіжий і корисний перекус на щодень.",
  },
  {
    title: "Мічелада",
    image: "/images/figma/recipes/michelada.jpg",
    description: "Мексиканський пивний коктейль зі спеціями.",
  },
  {
    title: "Вівчарський пиріг",
    image: "/images/figma/recipes/shepherds-pie.jpg",
    description: "Британська класика з картопляним пюре та м'ясом.",
  },
  {
    title: "Паста з горілкою та лимоном",
    image: "/images/figma/recipes/vodka-lemon-pasta.jpg",
    description: "Вершкова паста з цитрусовими нотками.",
  },
  {
    title: "Віденський шніцель",
    image: "/images/figma/recipes/viennese-schnitzel.jpg",
    description: "Хрустка класика австрійської кухні.",
  },
  {
    title: "Пісний салат з капусти з фініковою заправкою",
    image: "/images/figma/recipes/cabbage-date-salad.jpg",
    description: "Легкий і солодкуватий овочевий салат.",
  },
  {
    title: "Запечена редиска із соусом",
    image: "/images/figma/recipes/baked-radish.jpg",
    description: "Несподіваний гарнір з печеної редиски.",
  },
];

async function main() {
  console.log("🌱 Починаю seed...");

  const existingCount = await prisma.product.count();
  if (existingCount > 0) {
    console.log(`⚠️  В БД вже є ${existingCount} товарів. Пропускаю seed.`);
    console.log("   Якщо хочеш перезаповнити — спочатку запусти:");
    console.log("   node seed.js --force");

    if (!process.argv.includes("--force")) {
      return;
    }

    console.log("🗑️  Очищую таблиці...");
    await prisma.product.deleteMany();
    await prisma.recipe.deleteMany();
  }

  const result = await prisma.product.createMany({ data: products });
  console.log(
    `✅ Додано ${result.count} товарів у ${[...new Set(products.map((p) => p.category))].length} категоріях.`,
  );
  console.log(
    `   Унікальних підкатегорій: ${[...new Set(products.map((p) => p.subcategory).filter(Boolean))].length}`,
  );

  const recipeResult = await prisma.recipe.createMany({ data: recipes });
  console.log(`✅ Додано ${recipeResult.count} рецептів.`);
}

main()
  .catch((e) => {
    console.error("❌ Помилка seed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
