services:
  db:
    image: postgres:15-alpine
    container_name: silpo_db
    environment:
      POSTGRES_USER: silpo_admin
      POSTGRES_PASSWORD: silpo_password
      POSTGRES_DB: silpo_ecommerce
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
